"""Database creation

Revision ID: 56cb66339553
Revises: 
Create Date: 2023-05-23 21:33:28.701179

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '56cb66339553'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(), nullable=False),
                    sa.Column('permissions', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('username', sa.String(), nullable=False),
                    sa.Column('password', sa.String(), nullable=False),
                    sa.Column('registered_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('role_id', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
                    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('pgbench_accounts')
    op.drop_table('pgbench_history')
    op.drop_table('pgbench_tellers')
    op.drop_table('pgbench_branches')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pgbench_branches',
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bbalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=88), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('bid', name='pgbench_branches_pkey')
    )
    op.create_table('pgbench_tellers',
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tbalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=84), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('tid', name='pgbench_tellers_pkey')
    )
    op.create_table('pgbench_history',
    sa.Column('tid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('aid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('delta', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mtime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=22), autoincrement=False, nullable=True)
    )
    op.create_table('pgbench_accounts',
    sa.Column('aid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('bid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('abalance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('filler', sa.CHAR(length=84), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('aid', name='pgbench_accounts_pkey')
    )
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
